

TUNING.DISTPENALTY_MAXDAYS = GetModConfigData("maxdays")
TUNING.DISTPENALTY_MINDAYS = 0
TUNING.DISTPENALTY_MULTIPLIER = GetModConfigData("penaltymultiplier")
TUNING.DISTPENALTY_REBALANCE = GetModConfigData("rebalance")

if TUNING.DISTPENALTY_REBALANCE then

    -- Wilson
    
    -- Willow
    TUNING.WILLOW_FIRE_DAMAGE = 0

    -- Wolfgang
    TUNING.WOLFGANG_ATTACKMULT_MIGHTY_MAX = 1.5
    TUNING.WOLFGANG_ATTACKMULT_MIGHTY_MIN = 1
    TUNING.WOLFGANG_ATTACKMULT_NORMAL = 1
    TUNING.WOLFGANG_ATTACKMULT_WIMPY_MAX = 1
    TUNING.WOLFGANG_ATTACKMULT_WIMPY_MIN = 0

    -- Wendy

    -- WX78

    -- Wickerbottom

    -- Woodie
    TUNING.BEAVER_DAMAGE = 51
    TUNING.BEAVER_SANITY_PENALTY = 0

    -- Wes

    -- Waxwell

    -- Wigfrid
    TUNING.WATHGRITHR_DAMAGE_MULT = 1.01
    TUNING.WATHGRITHR_ABSORPTION = 0.01

    -- Webber

end

GLOBAL.STRINGS.NAMES.DISTPENALTY = "Escape Penalty"
