TUNING.DISTPENALTY_MAXDAYS = GetModConfigData("maxdays")
TUNING.DISTPENALTY_MINDAYS = 0
TUNING.DISTPENALTY_MULTIPLIER = GetModConfigData("penaltymultiplier")

GLOBAL.STRINGS.NAMES.DISTPENALTY = "Escape Penaty"
