

TUNING.DISTPENALTY_MAXDAYS = GetModConfigData("maxdays")
TUNING.DISTPENALTY_MINDAYS = 0
TUNING.DISTPENALTY_MULTIPLIER = GetModConfigData("penaltymultiplier")
TUNING.DISTPENALTY_REBALANCE = GetModConfigData("rebalance")

if TUNING.DISTPENALTY_REBALANCE then

    TUNING.WATHGRITHR_DAMAGE_MULT = 1.15
    TUNING.WATHGRITHR_ABSORPTION = 0.15

    TUNING.WOLFGANG_ATTACKMULT_MIGHTY_MAX = 1.75
    TUNING.WOLFGANG_ATTACKMULT_MIGHTY_MIN = 1
    TUNING.WOLFGANG_ATTACKMULT_NORMAL = 1
    TUNING.WOLFGANG_ATTACKMULT_WIMPY_MAX = 1
    TUNING.WOLFGANG_ATTACKMULT_WIMPY_MIN = 0

end

GLOBAL.STRINGS.NAMES.DISTPENALTY = "Escape Penaty"
